import { Challenge, Language } from './types';

export const languages: Language[] = [
  { id: 'agda', name: 'Agda' },
  { id: 'bf', name: 'BF' },
  { id: 'c', name: 'C' },
  { id: 'cfml', name: 'CFML' },
  { id: 'clojure', name: 'Clojure' },
  { id: 'cobol', name: 'COBOL' },
  { id: 'coffeescript', name: 'CoffeeScript' },
  { id: 'commonlisp', name: 'CommonLisp' },
  { id: 'coq', name: 'Coq' },
  { id: 'cpp', name: 'C++' },
  { id: 'crystal', name: 'Crystal' },
  { id: 'csharp', name: 'C#' },
  { id: 'd', name: 'D' },
  { id: 'dart', name: 'Dart' },
  { id: 'elixir', name: 'Elixir' },
  { id: 'elm', name: 'Elm' },
  { id: 'erlang', name: 'Erlang' },
  { id: 'factor', name: 'Factor' },
  { id: 'forth', name: 'Forth' },
  { id: 'fortran', name: 'Fortran' },
  { id: 'fsharp', name: 'F#' },
  { id: 'go', name: 'Go' },
  { id: 'groovy', name: 'Groovy' },
  { id: 'haskell', name: 'Haskell' },
  { id: 'haxe', name: 'Haxe' },
  { id: 'idris', name: 'Idris' },
  { id: 'java', name: 'Java' },
  { id: 'javascript', name: 'JavaScript' },
  { id: 'julia', name: 'Julia' },
  { id: 'kotlin', name: 'Kotlin' },
  { id: 'lambdacalc', name: 'λ Calculus' },
  { id: 'lean', name: 'Lean' },
  { id: 'lua', name: 'Lua' },
  { id: 'nasm', name: 'NASM' },
  { id: 'nim', name: 'Nim' },
  { id: 'objc', name: 'Objective-C' },
  { id: 'ocaml', name: 'OCaml' },
  { id: 'pascal', name: 'Pascal' },
  { id: 'perl', name: 'Perl' },
  { id: 'php', name: 'PHP' },
  { id: 'powershell', name: 'PowerShell' },
  { id: 'prolog', name: 'Prolog' },
  { id: 'purescript', name: 'PureScript' },
  { id: 'python', name: 'Python' },
  { id: 'r', name: 'R' },
  { id: 'racket', name: 'Racket' },
  { id: 'raku', name: 'Raku' },
  { id: 'reason', name: 'Reason' },
  { id: 'riscv', name: 'RISC-V' },
  { id: 'ruby', name: 'Ruby' },
  { id: 'rust', name: 'Rust' },
  { id: 'scala', name: 'Scala' },
  { id: 'shell', name: 'Shell' },
  { id: 'solidity', name: 'Solidity' },
  { id: 'sql', name: 'SQL' },
  { id: 'swift', name: 'Swift' },
  { id: 'typescript', name: 'TypeScript' },
  { id: 'vb', name: 'VB' },
];

export const rank: number[] = [-8, -7, -6, -5, -4, -3, -2, -1];

export const challengeList: Challenge[] = [
  {
    id: '5bb0c58f484fcd170700063d',
    name: 'Pillars',
    slug: 'pillars',
    category: 'reference',
    publishedAt: '2018-09-30T12:46:07.783Z',
    approvedAt: '2018-09-30T16:14:20.217Z',
    languages: [
      'javascript',
      'python',
      'ruby',
      'c',
      'haskell',
      'php',
      'cpp',
      'r',
      'scala',
      'julia',
      'cobol',
      'csharp',
    ],
    url: 'https://www.codewars.com/kata/5bb0c58f484fcd170700063d',
    rank: { id: -8, name: '8 kyu', color: 'white' },
    createdAt: '2018-09-30T12:46:29.627Z',
    createdBy: {
      username: 'petrosernivka',
      url: 'https://www.codewars.com/users/petrosernivka',
    },
    approvedBy: {
      username: 'Blind4Basics',
      url: 'https://www.codewars.com/users/Blind4Basics',
    },
    description:
      'There are pillars near the road. The distance between the pillars is the same and the width of the pillars is the same.\nYour function accepts three arguments:\n1. number of pillars (≥ 1);\n2. distance between pillars (10 - 30 meters);\n3. width of the pillar (10 - 50 centimeters).\n\nCalculate the distance between the first and the last pillar in centimeters (without the width of the first and last pillar).',
    totalAttempts: 33625,
    totalCompleted: 13223,
    totalStars: 124,
    voteScore: 1247,
    tags: ['Fundamentals', 'Mathematics'],
    contributorsWanted: true,
    unresolved: { issues: 0, suggestions: 3 },
  },
  {
    id: '5842df8ccbd22792a4000245',
    name: 'Write Number in Expanded Form',
    slug: 'write-number-in-expanded-form',
    category: 'reference',
    publishedAt: '2016-12-06T05:05:44.878Z',
    approvedAt: '2016-12-06T15:17:14.857Z',
    languages: [
      'javascript',
      'ruby',
      'python',
      'coffeescript',
      'haskell',
      'php',
      'java',
      'swift',
      'csharp',
      'fsharp',
      'rust',
      'c',
      'factor',
    ],
    url: 'https://www.codewars.com/kata/5842df8ccbd22792a4000245',
    rank: { id: -6, name: '6 kyu', color: 'yellow' },
    createdAt: '2016-12-03T15:06:52.647Z',
    createdBy: { username: 'Belax8', url: 'https://www.codewars.com/users/Belax8' },
    approvedBy: { username: 'suic', url: 'https://www.codewars.com/users/suic' },
    description:
      '# Write Number in Expanded Form\n\nYou will be given a number and you will need to return it as a string in [Expanded Form](https://www.mathsisfun.com/definitions/expanded-notation.html). For example:\n\n```haskell\nexpandedForm 12    -- Should return \'10 + 2\'\nexpandedForm 42    -- Should return \'40 + 2\'\nexpandedForm 70304 -- Should return \'70000 + 300 + 4\'\n```\n\n```javascript\nexpandedForm(12); // Should return \'10 + 2\'\nexpandedForm(42); // Should return \'40 + 2\'\nexpandedForm(70304); // Should return \'70000 + 300 + 4\'\n```\n```python\nexpanded_form(12) # Should return \'10 + 2\'\nexpanded_form(42) # Should return \'40 + 2\'\nexpanded_form(70304) # Should return \'70000 + 300 + 4\'\n```\n```php\nexpanded_form(12); // Should return "10 + 2"\nexpanded_form(42); // Should return "40 + 2"\nexpanded_form(70304); // Should return "70000 + 300 + 4"\n```\n```ruby\nexpanded_form(12); # Should return \'10 + 2\'\nexpanded_form(42); # Should return \'40 + 2\'\nexpanded_form(70304); # Should return \'70000 + 300 + 4\'\n```\n```coffeescript\nexpandedForm(12); # Should return \'10 + 2\'\nexpandedForm(42); # Should return \'40 + 2\'\nexpandedForm(70304); # Should return \'70000 + 300 + 4\'\n```\n```java\nKata.expandedForm(12); # Should return "10 + 2"\nKata.expandedForm(42); # Should return "40 + 2"\nKata.expandedForm(70304); # Should return "70000 + 300 + 4"\n```\n```csharp\nKata.ExpandedForm(12); # Should return "10 + 2"\nKata.ExpandedForm(42); # Should return "40 + 2"\nKata.ExpandedForm(70304); # Should return "70000 + 300 + 4"\n```\n```fsharp\nexpandedForm 12L // Should return "10 + 2"\nexpandedForm 42L // Should return "40 + 2"\nexpandedForm 70304L // Should return "70000 + 300 + 4"\n```\n```rust\nexpanded_form(12);    // Should return "10 + 2"\nexpanded_form(42);    // Should return "40 + 2"\nexpanded_form(70304); // Should return "70000 + 300 + 4"\n```\n\nNOTE: All numbers will be whole numbers greater than 0.\n\nIf you liked this kata, check out [part 2](https://www.codewars.com/kata/write-number-in-expanded-form-part-2)!!\n',
    totalAttempts: 237052,
    totalCompleted: 54665,
    totalStars: 1529,
    voteScore: 4749,
    tags: ['Strings', 'Mathematics', 'Algorithms', 'Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 12, suggestions: 6 },
  },
  {
    id: '57b06f90e298a7b53d000a86',
    name: 'The Supermarket Queue',
    slug: 'the-supermarket-queue',
    category: 'reference',
    publishedAt: '2016-08-14T14:29:29.351Z',
    approvedAt: '2016-08-20T16:52:54.006Z',
    languages: [
      'javascript',
      'python',
      'ruby',
      'cpp',
      'csharp',
      'java',
      'haskell',
      'fsharp',
      'c',
      'cobol',
      'julia',
      'rust',
      'd',
      'go',
    ],
    url: 'https://www.codewars.com/kata/57b06f90e298a7b53d000a86',
    rank: { id: -6, name: '6 kyu', color: 'yellow' },
    createdAt: '2016-08-14T13:18:08.128Z',
    createdBy: { username: 'mattlub', url: 'https://www.codewars.com/users/mattlub' },
    approvedBy: {
      username: 'GiacomoSorbi',
      url: 'https://www.codewars.com/users/GiacomoSorbi',
    },
    description:
      'There is a queue for the self-checkout tills at the supermarket. Your task is write a function to calculate the total time required for all the customers to check out!\n\n### input\n```if-not:c\n* customers: an array of positive integers representing the queue. Each integer represents a customer, and its value is the amount of time they require to check out.\n* n: a positive integer, the number of checkout tills.\n```\n```if:c\n* customers: a pointer to an array of positive integers representing the queue. Each integer represents a customer, and its value is the amount of time they require to check out.\n* customers_length: the length of the array that `customers` points to.\n* n: a positive integer, the number of checkout tills.\n```\n\n### output\nThe function should return an integer, the total time required.\n\n-------------------------------------------\n\n## Important\n**Please look at the examples and clarifications below, to ensure you understand the task correctly :)**\n\n-------\n\n### Examples\n\n```javascript\nqueueTime([5,3,4], 1)\n// should return 12\n// because when there is 1 till, the total time is just the sum of the times\n\nqueueTime([10,2,3,3], 2)\n// should return 10\n// because here n=2 and the 2nd, 3rd, and 4th people in the \n// queue finish before the 1st person has finished.\n\nqueueTime([2,3,10], 2)\n// should return 12\n```\n```haskell\nqueueTime [5,3,4] 1\n-- should return 12\n-- because when there is 1 till, the total time is just the sum of the times\n\nqueueTime [10,2,3,3] 2\n-- should return 10\n-- because here n=2 and the 2nd, 3rd, and 4th people in the \n-- queue finish before the 1st person has finished.\n\nqueueTime [2,3,10] 2\n-- should return 12\n```\n```python\nqueue_time([5,3,4], 1)\n# should return 12\n# because when n=1, the total time is just the sum of the times\n\nqueue_time([10,2,3,3], 2)\n# should return 10\n# because here n=2 and the 2nd, 3rd, and 4th people in the \n# queue finish before the 1st person has finished.\n\nqueue_time([2,3,10], 2)\n# should return 12\n```\n```ruby\nqueue_time([5,3,4], 1)\n# should return 12\n# because when n=1, the total time is just the sum of the times\n\nqueue_time([10,2,3,3], 2)\n# should return 10\n# because here n=2 and the 2nd, 3rd, and 4th people in the \n# queue finish before the 1st person has finished.\n\nqueue_time([2,3,10], 2)\n# should return 12\n```\n```cpp\nqueueTime(std::vector\u003cint\u003e{5,3,4}, 1)\n// should return 12\n// because when n=1, the total time is just the sum of the times\n\nqueueTime(std::vector\u003cint\u003e{10,2,3,3}, 2)\n// should return 10\n// because here n=2 and the 2nd, 3rd, and 4th people in the \n// queue finish before the 1st person has finished.\n\nqueueTime(std::vector\u003cint\u003e{2,3,10}, 2)\n// should return 12\n```\n```fsharp\nqueueTime [5;3;4] 1\n// should return 12\n// because when there is 1 till, the total time is just the sum of the times\n\nqueueTime [10;2;3;3] 2\n// should return 10\n// because here n=2 and the 2nd, 3rd, and 4th people in the \n// queue finish before the 1st person has finished.\n\nqueueTime [2;3;10] 2\n// should return 12\n```\n```c\nint customers1[] = {5, 3, 4};\nint customers1_length = 3;\nint n1 = 1;\nqueueTime(customers1, customers1_length, n1)\n// should return 12\n// because when n=1, the total time is just the sum of the times\n\nint customers2[] = {10, 2, 3, 3};\nint customers2_length = 4;\nint n2 = 2;\nqueueTime(customers2, customers2_length, n2)\n// should return 10\n// because here n=2 and the 2nd, 3rd, and 4th people in the \n// queue finish before the 1st person has finished.\n\nint customers3[] = {2, 3, 10};\nint customers3_length = 3;\nint n3 = 2;\nqueueTime(customers3, customers3_length, n3)\n// should return 12\n```\n```cobol\n      QueueTime [5,3,4] 1 =\u003e 12\n      * because when there is 1 till, the total time is just the sum of the times\n\n      QueueTime [10,2,3,3] 2 =\u003e 10\n      *  because here n=2 and the 2nd, 3rd, and 4th people in the \n      * queue finish before the 1st person has finished.\n\n      QueueTime [2,3,10] 2 =\u003e 12\n```\n\n### Clarifications\n\n * There is only ONE queue serving many tills, and\n * The order of the queue NEVER changes, and\n * The front person in the queue (i.e. the first element in the array/list) proceeds to a till as soon as it becomes free.\n\nN.B. You should assume that all the test input will be valid, as specified above.\n\nP.S. The situation in this kata can be likened to the more-computer-science-related idea of a thread pool, with relation to running multiple processes at the same time: https://en.wikipedia.org/wiki/Thread_pool\n',
    totalAttempts: 226444,
    totalCompleted: 35768,
    totalStars: 3568,
    voteScore: 4156,
    tags: ['Arrays', 'Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 1, suggestions: 2 },
  },
  {
    id: '56262d569049f85ea00000af',
    name: 'Pangrams',
    slug: 'pangrams',
    category: 'algorithms',
    publishedAt: null,
    approvedAt: null,
    languages: ['ruby'],
    url: 'https://www.codewars.com/kata/56262d569049f85ea00000af',
    rank: { id: null, name: null, color: null },
    createdAt: '2015-10-20T12:02:31.235Z',
    createdBy: { username: 'jdubya', url: 'https://www.codewars.com/users/jdubya' },
    description:
      "A pangram is a sentence/string that contains every letter of the alphabet. \n\nWrite a function called `is_pangram?` that takes in a string and returns true if the string contains every letter of the alphabet, false if it does not.\n\nFor example:\n\n```rb\nis_pangram?('The quick brown fox jumps over the lazy dog') #=\u003e true\nis_pangram?('hello world') #=\u003e false\n\n```",
    totalAttempts: 0,
    totalCompleted: 0,
    totalStars: 0,
    voteScore: 0,
    tags: ['Strings', 'Algorithms'],
    contributorsWanted: true,
    unresolved: { issues: 0, suggestions: 0 },
  },
  {
    id: '5839edaa6754d6fec10000a2',
    name: 'Find the missing letter',
    slug: 'find-the-missing-letter',
    category: 'algorithms',
    publishedAt: '2016-11-26T20:55:30.705Z',
    approvedAt: '2016-11-28T23:29:54.618Z',
    languages: [
      'csharp',
      'fsharp',
      'java',
      'javascript',
      'python',
      'ruby',
      'crystal',
      'typescript',
      'haskell',
      'php',
      'c',
      'coffeescript',
      'objc',
      'nasm',
      'scala',
      'kotlin',
      'rust',
      'julia',
      'racket',
      'swift',
      'go',
      'bf',
      'factor',
    ],
    url: 'https://www.codewars.com/kata/5839edaa6754d6fec10000a2',
    rank: { id: -6, name: '6 kyu', color: 'yellow' },
    createdAt: '2016-11-26T20:16:42.630Z',
    createdBy: {
      username: 'user5036852',
      url: 'https://www.codewars.com/users/user5036852',
    },
    approvedBy: {
      username: 'GiacomoSorbi',
      url: 'https://www.codewars.com/users/GiacomoSorbi',
    },
    description:
      '# Find the missing letter\n\nWrite a method that takes an array of consecutive (increasing) letters as input and that returns the missing letter in the array.\n\n~~~if:factor\nIn the case of factor, your array of letters will be a string.\n~~~\n\nYou will always get an valid array. And it will be always exactly one letter be missing. The length of the array will always be at least 2.\u003cbr\u003e\nThe array will always contain letters in only one case.\n\nExample:\n~~~if-not:swift,factor\n```\n[\'a\',\'b\',\'c\',\'d\',\'f\'] -\u003e \'e\'\n[\'O\',\'Q\',\'R\',\'S\'] -\u003e \'P\'\n```\n~~~\n\n~~~if:factor\n```factor\n"abcdf" -\u003e CHAR: e\n"OQRS" -\u003e CHAR: P\n```\n~~~\n\n```if:swift\n["a","b","c","d","f"] -\u003e "e"\n["O","Q","R","S"] -\u003e "P"\n```\n\n(Use the English alphabet with 26 letters!)\n\nHave fun coding it and please don\'t forget to vote and rank this kata! :-) \n\nI have also created other katas. Take a look if you enjoyed this kata!',
    totalAttempts: 233610,
    totalCompleted: 73390,
    totalStars: 1254,
    voteScore: 6570,
    tags: ['Mathematics', 'Algorithms'],
    contributorsWanted: false,
    unresolved: { issues: 4, suggestions: 2 },
  },
  {
    id: '525c65e51bf619685c000059',
    name: 'Pete, the baker',
    slug: 'pete-the-baker',
    category: 'algorithms',
    publishedAt: '2013-10-14T22:22:43.459Z',
    approvedAt: null,
    languages: ['javascript', 'haskell', 'coffeescript', 'python', 'ruby', 'go', 'factor'],
    url: 'https://www.codewars.com/kata/525c65e51bf619685c000059',
    rank: { id: -5, name: '5 kyu', color: 'yellow' },
    createdAt: '2013-10-14T21:45:09.395Z',
    createdBy: {
      username: 'BattleRattle',
      url: 'https://www.codewars.com/users/BattleRattle',
    },
    description:
      'Pete likes to bake some cakes. He has some recipes and ingredients. Unfortunately he is not good in maths. Can you help him to find out, how many cakes he could bake considering his recipes?\n\n~~~if-not:factor\nWrite a function `cakes()`, which takes the recipe (object) and the available ingredients (also an object) and returns the maximum number of cakes Pete can bake (integer). For simplicity there are no units for the amounts (e.g. 1 lb of flour or 200 g of sugar are simply 1 or 200). Ingredients that are not present in the objects, can be considered as 0.\n~~~\n~~~if:factor\nWrite a word `cakes`, which takes a recipe (assoc) and the available ingredients (also an assoc) and returns the maximum number of cakes Pete can bake (integer). For simplicity there are no units for the amounts (e.g. 1 lb of flour or 200 g of sugar are simply 1 or 200). Ingredients for the recipe that are not present can be considered as 0.\n~~~\n\nExamples:\n\n```javascript\n// must return 2\ncakes({flour: 500, sugar: 200, eggs: 1}, {flour: 1200, sugar: 1200, eggs: 5, milk: 200}); \n// must return 0\ncakes({apples: 3, flour: 300, sugar: 150, milk: 100, oil: 100}, {sugar: 500, flour: 2000, milk: 2000}); \n```\n```coffeescript\n# must return 2\ncakes({flour: 500, sugar: 200, eggs: 1}, {flour: 1200, sugar: 1200, eggs: 5, milk: 200}) \n# must return 0\ncakes({apples: 3, flour: 300, sugar: 150, milk: 100, oil: 100}, {sugar: 500, flour: 2000, milk: 2000}) \n```\n```python\n# must return 2\ncakes({flour: 500, sugar: 200, eggs: 1}, {flour: 1200, sugar: 1200, eggs: 5, milk: 200})\n# must return 0\ncakes({apples: 3, flour: 300, sugar: 150, milk: 100, oil: 100}, {sugar: 500, flour: 2000, milk: 2000})\n```\n```haskell\ncakes [("flour",500), ("sugar",200), ("eggs",1)] [("flour",1200), ("sugar",1200), ("eggs",5), ("milk",200)]  `shouldBe` 2\ncakes [("apples",3), ("flour",300), ("sugar",150), ("milk",100), ("oil",100)] [("sugar",500), ("flour",2000), ("milk",2000)] `shouldBe` 0\n```\n```factor\n{ { "flour" 500 } { "sugar" 200 } { "eggs" 1 } } { { "flour" 1200 } { "sugar" 1200 } { "eggs" 5 } { "milk" 200 } } cakes -\u003e  2\n{ { "apples" 3 } { "flour" 300 } { "sugar" 150 } { "milk" 100 } { "oil" 100 } } { { "sugar" 500 } { "flour" 2000 } { "milk" 2000 } } cakes -\u003e 0\n```',
    totalAttempts: 183909,
    totalCompleted: 50513,
    totalStars: 1245,
    voteScore: 3731,
    tags: ['Algorithms'],
    contributorsWanted: true,
    unresolved: { issues: 4, suggestions: 9 },
  },
  {
    id: '5314b3c6bb244a48ab00076c',
    name: 'Luck check',
    slug: 'luck-check',
    category: 'games',
    publishedAt: '2014-03-03T16:55:38.005Z',
    approvedAt: '2014-04-18T00:38:14.245Z',
    languages: ['ruby', 'python', 'javascript', 'rust', 'scala'],
    url: 'https://www.codewars.com/kata/5314b3c6bb244a48ab00076c',
    rank: { id: -5, name: '5 kyu', color: 'yellow' },
    createdAt: '2014-03-03T16:54:30.389Z',
    createdBy: {
      username: 'SundaySalsa',
      url: 'https://www.codewars.com/users/SundaySalsa',
    },
    approvedBy: { username: 'jhoffner', url: 'https://www.codewars.com/users/jhoffner' },
    description:
      "In some countries of former Soviet Union there was a belief about lucky tickets. A transport ticket of any sort was believed to posess luck if sum of digits on the left half of its number was equal to the sum of digits on the right half. Here are examples of such numbers:\n\n```\n003111    #             3 = 1 + 1 + 1\n813372    #     8 + 1 + 3 = 3 + 7 + 2\n17935     #         1 + 7 = 3 + 5  // if the length is odd, you should ignore the middle number when adding the halves.\n56328116  # 5 + 6 + 3 + 2 = 8 + 1 + 1 + 6\n```\nSuch tickets were either eaten after being used or collected for bragging rights.\n\nYour task is to write a funtion ```luck_check(str)```, which returns ```true/True``` if argument is string decimal representation of a lucky ticket number, or ```false/False``` for all other numbers. It should throw errors for empty strings or strings which don't represent a decimal number.",
    totalAttempts: 34265,
    totalCompleted: 3297,
    totalStars: 85,
    voteScore: 316,
    tags: ['Strings', 'Mathematics', 'Puzzles'],
    contributorsWanted: true,
    unresolved: { issues: 6, suggestions: 2 },
  },
  {
    id: '54ff0d1f355cfd20e60001fc',
    name: 'Factorial',
    slug: 'factorial',
    category: 'reference',
    publishedAt: '2015-03-10T15:27:17.653Z',
    approvedAt: '2015-06-05T18:03:43.062Z',
    languages: ['csharp', 'java', 'javascript', 'php', 'python', 'c', 'factor'],
    url: 'https://www.codewars.com/kata/54ff0d1f355cfd20e60001fc',
    rank: { id: -7, name: '7 kyu', color: 'white' },
    createdAt: '2015-03-10T15:26:23.601Z',
    createdBy: { username: 'zvytas', url: 'https://www.codewars.com/users/zvytas' },
    approvedBy: { username: 'jhoffner', url: 'https://www.codewars.com/users/jhoffner' },
    description:
      'In mathematics, the factorial of a non-negative integer n, denoted by n!, is the product of all positive integers less than or equal to n. For example:\n5! = 5 \\* 4 \\* 3 \\* 2 \\* 1 = 120. By convention the value of 0! is 1.\n\n~~~if-not:factor\nWrite a function to calculate factorial for a given input. If input is below 0 or above 12 throw an exception of type `ArgumentOutOfRangeException` (C#) or `IllegalArgumentException` (Java) or `RangeException` (PHP) or throw a `RangeError` (JavaScript) or `ValueError` (Python) or return `-1` (C).\n~~~\n\n~~~if:factor\nWrite a word to calculate factorial for a given input. If input is below 0 or above 12 throw an error using the given word `range-error`.\n~~~\n\nMore details about factorial can be found [here](https://www.wikiwand.com/en/Factorial).',
    totalAttempts: 219945,
    totalCompleted: 32409,
    totalStars: 310,
    voteScore: 2253,
    tags: ['Algorithms', 'Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 1, suggestions: 0 },
  },
  {
    id: '5656b6906de340bd1b0000ac',
    name: 'Two to One',
    slug: 'two-to-one',
    category: 'reference',
    publishedAt: '2015-11-26T07:37:03.397Z',
    approvedAt: '2015-11-26T22:34:53.027Z',
    languages: [
      'java',
      'csharp',
      'ruby',
      'python',
      'javascript',
      'coffeescript',
      'haskell',
      'clojure',
      'cpp',
      'php',
      'crystal',
      'fsharp',
      'c',
      'elixir',
      'typescript',
      'shell',
      'ocaml',
      'kotlin',
      'julia',
      'go',
      'r',
      'rust',
      'scala',
      'powershell',
      'nim',
      'reason',
      'racket',
      'dart',
      'pascal',
      'perl',
      'cobol',
      'd',
      'erlang',
    ],
    url: 'https://www.codewars.com/kata/5656b6906de340bd1b0000ac',
    rank: { id: -7, name: '7 kyu', color: 'white' },
    createdAt: '2015-11-26T07:36:48.966Z',
    createdBy: { username: 'g964', url: 'https://www.codewars.com/users/g964' },
    approvedBy: { username: 'joh_pot', url: 'https://www.codewars.com/users/joh_pot' },
    description:
      'Take 2 strings `s1` and `s2` including only letters from `a` to `z`.\nReturn a new **sorted** string, the longest possible, containing distinct letters - each taken only once - coming from s1 or s2.\n\n#### Examples:\n```\na = "xyaabbbccccdefww"\nb = "xxxxyyyyabklmopq"\nlongest(a, b) -\u003e "abcdefklmopqwxy"\n\na = "abcdefghijklmnopqrstuvwxyz"\nlongest(a, a) -\u003e "abcdefghijklmnopqrstuvwxyz"\n```\n',
    totalAttempts: 343813,
    totalCompleted: 118765,
    totalStars: 1513,
    voteScore: 9697,
    tags: ['Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 1, suggestions: 5 },
  },
  {
    id: '55d24f55d7dd296eb9000030',
    name: 'Grasshopper - Summation',
    slug: 'grasshopper-summation',
    category: 'reference',
    publishedAt: '2015-09-03T18:12:44.351Z',
    approvedAt: '2015-09-11T02:33:00.119Z',
    languages: [
      'javascript',
      'ruby',
      'python',
      'coffeescript',
      'elixir',
      'php',
      'cpp',
      'csharp',
      'java',
      'crystal',
      'bf',
      'typescript',
      'scala',
      'haskell',
      'groovy',
      'kotlin',
      'nasm',
      'julia',
      'dart',
      'r',
      'reason',
      'nim',
      'racket',
      'factor',
      'go',
      'clojure',
      'elm',
      'purescript',
      'forth',
      'c',
      'lua',
      'cfml',
      'erlang',
      'fortran',
      'fsharp',
      'powershell',
      'prolog',
      'solidity',
      'swift',
      'vb',
      'shell',
      'objc',
      'rust',
      'perl',
      'raku',
      'ocaml',
      'commonlisp',
      'pascal',
      'haxe',
      'cobol',
      'd',
    ],
    url: 'https://www.codewars.com/kata/55d24f55d7dd296eb9000030',
    rank: { id: -8, name: '8 kyu', color: 'white' },
    createdAt: '2015-08-17T21:17:09.547Z',
    createdBy: {
      username: 'danleavitt0',
      url: 'https://www.codewars.com/users/danleavitt0',
    },
    approvedBy: { username: 'joh_pot', url: 'https://www.codewars.com/users/joh_pot' },
    description:
      '# Summation\n\nWrite a program that finds the summation of every number from 1 to num. The number will always be a positive integer greater than 0.\n\nFor example:\n```if-not:racket\n~~~\nsummation(2) -\u003e 3\n1 + 2\n\nsummation(8) -\u003e 36\n1 + 2 + 3 + 4 + 5 + 6 + 7 + 8\n~~~\n```\n```if:racket\n~~~racket\n(summation 2) ; 3  (+ 1 2)\n(summation 8) ; 36 (+ 1 2 3 4 5 6 7 8)\n~~~\n```\n',
    totalAttempts: 311642,
    totalCompleted: 154514,
    totalStars: 976,
    voteScore: 10538,
    tags: ['Fundamentals', 'Mathematics'],
    contributorsWanted: true,
    unresolved: { issues: 1, suggestions: 1 },
  },
  {
    id: '53dbd5315a3c69eed20002dd',
    name: 'List Filtering',
    slug: 'list-filtering',
    category: 'reference',
    publishedAt: '2014-08-01T17:58:35.185Z',
    approvedAt: '2014-08-13T04:24:50.513Z',
    languages: [
      'python',
      'ruby',
      'coffeescript',
      'javascript',
      'csharp',
      'fsharp',
      'java',
      'factor',
      'scala',
    ],
    url: 'https://www.codewars.com/kata/53dbd5315a3c69eed20002dd',
    rank: { id: -7, name: '7 kyu', color: 'white' },
    createdAt: '2014-08-01T17:58:09.749Z',
    createdBy: { username: 'cmgerber', url: 'https://www.codewars.com/users/cmgerber' },
    approvedBy: { username: 'jhoffner', url: 'https://www.codewars.com/users/jhoffner' },
    description:
      'In this kata you will create a function that takes a list of non-negative integers and strings and returns a new list with the strings filtered out.\n\n### Example\n\n```python\nfilter_list([1,2,\'a\',\'b\']) == [1,2]\nfilter_list([1,\'a\',\'b\',0,15]) == [1,0,15]\nfilter_list([1,2,\'aasf\',\'1\',\'123\',123]) == [1,2,123]\n```\n```csharp\nListFilterer.GetIntegersFromList(new List\u003cobject\u003e(){1, 2, "a", "b"}) =\u003e {1, 2}\nListFilterer.GetIntegersFromList(new List\u003cobject\u003e(){1, 2, "a", "b", 0, 15}) =\u003e {1, 2, 0, 15}\nListFilterer.GetIntegersFromList(new List\u003cobject\u003e(){1, 2, "a", "b", "aasf", "1", "123", 231}) =\u003e {1, 2, 231}\n```\n```factor\n{ 1 2 "a" "b" } filter-seq ! { 1 2 }\n{ 1 "a" "b" 0 15 } filter-seq ! { 1 0 15 }\n{ 1 2 "aasf" "1" "123" 123 } filter-seq ! { 1 2 123 }\n```\n```java\nKata.filterList(List.of(1, 2, "a", "b")) =\u003e List.of(1,2)\nKata.filterList(List.of(1, 2, "a", "b", 0, 15)) =\u003e List.of(1,2,0,15)\nKata.filterList(List.of(1, 2, "a", "b", "aasf", "1", "123", 231)) =\u003e List.of(1, 2, 231)\n```\n```scala\nfilterList(List(1, 2, "a", "b")) == List(1, 2)\nfilterList(List(1, "a", "b", 0, 15)) == List(1, 0, 15)\nfilterList(List(1, 2, "aasf", "1", "123", 123)) == List(1, 2, 123)\n```',
    totalAttempts: 466210,
    totalCompleted: 182787,
    totalStars: 1251,
    voteScore: 13904,
    tags: ['Lists', 'Filtering', 'Data Structures', 'Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 2, suggestions: 4 },
  },
  {
    id: '53369039d7ab3ac506000467',
    name: "Convert boolean values to strings 'Yes' or 'No'.",
    slug: 'convert-boolean-values-to-strings-yes-or-no',
    category: 'reference',
    publishedAt: '2014-03-29T09:19:53.875Z',
    approvedAt: '2014-05-29T00:01:04.493Z',
    languages: [
      'ruby',
      'python',
      'haskell',
      'java',
      'javascript',
      'csharp',
      'elixir',
      'cpp',
      'c',
      'php',
      'typescript',
      'go',
      'julia',
      'nasm',
      'dart',
      'racket',
      'prolog',
      'swift',
      'crystal',
      'scala',
      'rust',
      'coffeescript',
      'r',
      'perl',
      'lua',
      'd',
      'sql',
    ],
    url: 'https://www.codewars.com/kata/53369039d7ab3ac506000467',
    rank: { id: -8, name: '8 kyu', color: 'white' },
    createdAt: '2014-03-29T09:20:08.629Z',
    createdBy: {
      username: 'weavermedia',
      url: 'https://www.codewars.com/users/weavermedia',
    },
    approvedBy: { username: 'jhoffner', url: 'https://www.codewars.com/users/jhoffner' },
    description:
      'Complete the method that takes a boolean value and return a `"Yes"` string for `true`, or a `"No"` string for `false`.\n',
    totalAttempts: 369126,
    totalCompleted: 202808,
    totalStars: 753,
    voteScore: 12421,
    tags: ['Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 2, suggestions: 0 },
  },
  {
    id: '520b9d2ad5c005041100000f',
    name: 'Simple Pig Latin',
    slug: 'simple-pig-latin',
    category: 'algorithms',
    publishedAt: '2013-08-14T15:07:22.841Z',
    approvedAt: null,
    languages: [
      'javascript',
      'coffeescript',
      'ruby',
      'python',
      'csharp',
      'objc',
      'cpp',
      'java',
      'clojure',
      'typescript',
    ],
    url: 'https://www.codewars.com/kata/520b9d2ad5c005041100000f',
    rank: { id: -5, name: '5 kyu', color: 'yellow' },
    createdAt: '2013-08-14T15:07:23.373Z',
    createdBy: {
      username: 'user2505876',
      url: 'https://www.codewars.com/users/user2505876',
    },
    description:
      'Move the first letter of each word to the end of it, then add "ay" to the end of the word. Leave punctuation marks untouched.\n\n## Examples\n\n```javascript\npigIt(\'Pig latin is cool\'); // igPay atinlay siay oolcay\npigIt(\'Hello world !\');     // elloHay orldway !\n```\n```objc\npigIt(@"Pig latin is cool"); // =\u003e @"igPay atinlay siay oolcay"\npigIt(@"Hello world !");     // =\u003e @"elloHay orldway !"\n```\n```ruby\npig_it(\'Pig latin is cool\') # igPay atinlay siay oolcay\npig_it(\'Hello world !\')     # elloHay orldway !\n```\n```python\npig_it(\'Pig latin is cool\') # igPay atinlay siay oolcay\npig_it(\'Hello world !\')     # elloHay orldway !\n```\n```csharp\nKata.PigIt("Pig latin is cool"); // igPay atinlay siay oolcay\nKata.PigIt("Hello world !");     // elloHay orldway !\n```\n```C++\npig_it("Pig latin is cool");   // igPay atinlay siay oolcay\npig_it("Hello world !");       // elloHay orldway\n```\n```Java\nPigLatin.pigIt(\'Pig latin is cool\'); // igPay atinlay siay oolcay\nPigLatin.pigIt(\'Hello world !\');     // elloHay orldway !\n```\n```clojure\n(piglatin/pig-it "Pig latin is cool") ; "igPay atinlay siay oolcay"\n(piglatin/pig-it "Hello world !")     ; "elloHay orldway !"\n```\n```typescript\npigIt(\'Pig latin is cool\'); // igPay atinlay siay oolcay\npigIt(\'Hello world !\');     // elloHay orldway !\n```\n',
    totalAttempts: 638499,
    totalCompleted: 116346,
    totalStars: 1801,
    voteScore: 7074,
    tags: ['Regular Expressions', 'Algorithms'],
    contributorsWanted: true,
    unresolved: { issues: 7, suggestions: 23 },
  },
  {
    id: '54c27a33fb7da0db0100040e',
    name: "You're a square!",
    slug: 'youre-a-square',
    category: 'reference',
    publishedAt: '2015-01-23T16:56:54.174Z',
    approvedAt: '2015-01-28T16:38:49.582Z',
    languages: [
      'haskell',
      'javascript',
      'ruby',
      'coffeescript',
      'python',
      'java',
      'csharp',
      'dart',
      'typescript',
      'cpp',
      'scala',
      'c',
      'julia',
      'elixir',
      'commonlisp',
      'cobol',
      'r',
      'crystal',
      'php',
      'rust',
      'lua',
      'd',
    ],
    url: 'https://www.codewars.com/kata/54c27a33fb7da0db0100040e',
    rank: { id: -7, name: '7 kyu', color: 'white' },
    createdAt: '2015-01-23T16:43:31.249Z',
    createdBy: { username: 'bkaes', url: 'https://www.codewars.com/users/bkaes' },
    approvedBy: { username: 'jhoffner', url: 'https://www.codewars.com/users/jhoffner' },
    description:
      "### A square of squares\n\nYou like building blocks. You especially like building blocks that are squares. And what you even like more, is to arrange them into a square of square building blocks!\n\nHowever, sometimes, you can't arrange them into a square. Instead, you end up with an ordinary rectangle! Those blasted things! If you just had a way to know, whether you're currently working in vain… Wait! That's it! You just have to check if your number of building blocks is a _perfect square_.\n\n### Task\n\nGiven an integral number, determine if it's a [square number](https://en.wikipedia.org/wiki/Square_number):\n\n\u003e In mathematics, a __square number__ or __perfect square__ is an integer that is the square of an integer; in other words, it is the product of some integer with itself.\n\nThe tests will _always_ use some integral number, so don't worry about that in dynamic typed languages.\n\n### Examples\n\n```\n-1  =\u003e  false\n 0  =\u003e  true\n 3  =\u003e  false\n 4  =\u003e  true\n25  =\u003e  true\n26  =\u003e  false\n```",
    totalAttempts: 634864,
    totalCompleted: 195214,
    totalStars: 1659,
    voteScore: 14205,
    tags: ['Fundamentals', 'Mathematics'],
    contributorsWanted: true,
    unresolved: { issues: 0, suggestions: 3 },
  },
  {
    id: '5467e4d82edf8bbf40000155',
    name: 'Descending Order',
    slug: 'descending-order',
    category: 'reference',
    publishedAt: '2014-11-15T23:42:16.753Z',
    approvedAt: '2014-12-08T16:30:06.868Z',
    languages: [
      'python',
      'haskell',
      'javascript',
      'ruby',
      'clojure',
      'csharp',
      'java',
      'rust',
      'swift',
      'typescript',
      'fsharp',
      'php',
      'scala',
      'julia',
      'prolog',
      'elixir',
      'c',
      'cpp',
      'r',
      'crystal',
      'coffeescript',
      'cobol',
    ],
    url: 'https://www.codewars.com/kata/5467e4d82edf8bbf40000155',
    rank: { id: -7, name: '7 kyu', color: 'white' },
    createdAt: '2014-11-15T23:42:22.112Z',
    createdBy: { username: 'TastyOs', url: 'https://www.codewars.com/users/TastyOs' },
    approvedBy: { username: 'jhoffner', url: 'https://www.codewars.com/users/jhoffner' },
    description:
      'Your task is to make a function that can take any non-negative integer as an argument and return it with its digits in descending order. Essentially, rearrange the digits to create the highest possible number.\n\n\n### Examples:\n\nInput: `42145`\nOutput: `54421`\n\nInput: `145263`\nOutput: `654321`\n\nInput: `123456789`\nOutput: `987654321`\n\n',
    totalAttempts: 703542,
    totalCompleted: 190831,
    totalStars: 2418,
    voteScore: 15494,
    tags: ['Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 1, suggestions: 1 },
  },
  {
    id: '5265326f5fda8eb1160004c8',
    name: 'Convert a Number to a String!',
    slug: 'convert-a-number-to-a-string',
    category: 'reference',
    publishedAt: '2013-10-25T08:36:37.694Z',
    approvedAt: null,
    languages: [
      'javascript',
      'ruby',
      'coffeescript',
      'haskell',
      'python',
      'clojure',
      'java',
      'elixir',
      'rust',
      'csharp',
      'typescript',
      'crystal',
      'kotlin',
      'php',
      'scala',
      'c',
      'dart',
      'racket',
      'cpp',
      'julia',
      'reason',
      'r',
      'perl',
      'cobol',
      'swift',
      'factor',
      'd',
      'go',
      'riscv',
    ],
    url: 'https://www.codewars.com/kata/5265326f5fda8eb1160004c8',
    rank: { id: -8, name: '8 kyu', color: 'white' },
    createdAt: '2013-10-21T13:55:59.624Z',
    createdBy: { username: 'AKJ.IO', url: 'https://www.codewars.com/users/AKJ.IO' },
    description:
      'We need a function that can transform a number (integer) into a string.\n\nWhat ways of achieving this do you know?\n\n```if:c\nIn C, return a dynamically allocated string that will be freed by the test suite.\n```\n\n#### Examples (input --\u003e output):\n\n```\n123  --\u003e "123"\n999  --\u003e "999"\n-100 --\u003e "-100"\n```\n\n~~~if:riscv\nRISC-V: The function signature is:\n\n```c\nvoid number_to_string(int n, char *out);\n```\n\nConvert the input number `n` to a string, and write the result to `out`. You may assume `out` is large enough to hold the result. You do not need to return anything.\n~~~',
    totalAttempts: 369677,
    totalCompleted: 214018,
    totalStars: 695,
    voteScore: 12148,
    tags: ['Strings', 'Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 1, suggestions: 0 },
  },
  {
    id: '578553c3a1b8d5c40300037c',
    name: 'Ones and Zeros',
    slug: 'ones-and-zeros',
    category: 'reference',
    publishedAt: '2016-07-12T20:32:10.254Z',
    approvedAt: '2016-07-13T19:41:27.063Z',
    languages: [
      'java',
      'javascript',
      'python',
      'ruby',
      'coffeescript',
      'c',
      'csharp',
      'nasm',
      'php',
      'haskell',
      'crystal',
      'dart',
      'rust',
      'julia',
      'cobol',
      'typescript',
      'd',
    ],
    url: 'https://www.codewars.com/kata/578553c3a1b8d5c40300037c',
    rank: { id: -7, name: '7 kyu', color: 'white' },
    createdAt: '2016-07-12T20:32:04.213Z',
    createdBy: {
      username: 'user4386369',
      url: 'https://www.codewars.com/users/user4386369',
    },
    approvedBy: { username: 'smile67', url: 'https://www.codewars.com/users/smile67' },
    description:
      'Given an array of ones and zeroes, convert the equivalent binary value to an integer.\n\nEg: `[0, 0, 0, 1]` is treated as `0001` which is the binary representation of `1`.\n\nExamples:\n```\nTesting: [0, 0, 0, 1] ==\u003e 1\nTesting: [0, 0, 1, 0] ==\u003e 2\nTesting: [0, 1, 0, 1] ==\u003e 5\nTesting: [1, 0, 0, 1] ==\u003e 9\nTesting: [0, 0, 1, 0] ==\u003e 2\nTesting: [0, 1, 1, 0] ==\u003e 6\nTesting: [1, 1, 1, 1] ==\u003e 15\nTesting: [1, 0, 1, 1] ==\u003e 11\n```\n\nHowever, the arrays can have varying lengths, not just limited to `4`.',
    totalAttempts: 261100,
    totalCompleted: 100859,
    totalStars: 1132,
    voteScore: 7792,
    tags: ['Fundamentals', 'Arrays'],
    contributorsWanted: true,
    unresolved: { issues: 2, suggestions: 1 },
  },
  {
    id: '56dec885c54a926dcd001095',
    name: 'Opposite number',
    slug: 'opposite-number',
    category: 'reference',
    publishedAt: '2016-03-08T15:12:28.753Z',
    approvedAt: '2016-03-28T16:40:25.855Z',
    languages: [
      'ruby',
      'javascript',
      'coffeescript',
      'python',
      'csharp',
      'java',
      'haskell',
      'clojure',
      'cpp',
      'php',
      'elixir',
      'c',
      'go',
      'rust',
      'typescript',
      'swift',
      'lua',
      'shell',
      'julia',
      'groovy',
      'kotlin',
      'crystal',
      'nasm',
      'r',
      'nim',
      'ocaml',
      'scala',
      'purescript',
      'racket',
      'dart',
      'forth',
      'vb',
      'factor',
      'cfml',
      'sql',
      'elm',
      'perl',
      'cobol',
      'd',
    ],
    url: 'https://www.codewars.com/kata/56dec885c54a926dcd001095',
    rank: { id: -8, name: '8 kyu', color: 'white' },
    createdAt: '2016-03-08T12:41:42.047Z',
    createdBy: { username: 'sergioet', url: 'https://www.codewars.com/users/sergioet' },
    approvedBy: {
      username: 'GiacomoSorbi',
      url: 'https://www.codewars.com/users/GiacomoSorbi',
    },
    description:
      'Very simple, given an integer or a floating-point number, find its opposite.\n\nExamples:\n```\n1: -1\n14: -14\n-34: 34\n```\n\n~~~if:sql\nYou will be given a table: `opposite`, with a column: `number`. Return a table with a column: `res`.\n~~~\n',
    totalAttempts: 416782,
    totalCompleted: 224295,
    totalStars: 838,
    voteScore: 12325,
    tags: ['Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 1, suggestions: 0 },
  },
  {
    id: '551b4501ac0447318f0009cd',
    name: 'Convert a Boolean to a String',
    slug: 'convert-a-boolean-to-a-string',
    category: 'reference',
    publishedAt: '2015-04-01T01:08:58.056Z',
    approvedAt: '2015-10-07T17:01:04.327Z',
    languages: [
      'ruby',
      'python',
      'javascript',
      'java',
      'coffeescript',
      'csharp',
      'swift',
      'nasm',
      'typescript',
      'cpp',
      'julia',
      'rust',
      'c',
      'factor',
      'crystal',
      'dart',
      'haskell',
      'groovy',
      'r',
      'elixir',
      'cobol',
      'lua',
      'php',
      'd',
    ],
    url: 'https://www.codewars.com/kata/551b4501ac0447318f0009cd',
    rank: { id: -8, name: '8 kyu', color: 'white' },
    createdAt: '2015-04-01T01:08:17.546Z',
    createdBy: { username: 'btaitelb', url: 'https://www.codewars.com/users/btaitelb' },
    approvedBy: {
      username: 'ZozoFouchtra',
      url: 'https://www.codewars.com/users/ZozoFouchtra',
    },
    description:
      'Implement a function which convert the given boolean value into its string representation.\n\nNote: Only valid inputs will be given.\n',
    totalAttempts: 169105,
    totalCompleted: 110502,
    totalStars: 403,
    voteScore: 6047,
    tags: ['Strings', 'Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 1, suggestions: 1 },
  },
  {
    id: '5168bb5dfe9a00b126000018',
    name: 'Reversed Strings',
    slug: 'reversed-strings',
    category: 'reference',
    publishedAt: '2013-04-13T02:22:17.697Z',
    approvedAt: null,
    languages: [
      'javascript',
      'coffeescript',
      'ruby',
      'python',
      'dart',
      'php',
      'csharp',
      'java',
      'nim',
      'haskell',
      'rust',
      'groovy',
      'scala',
      'cpp',
      'go',
      'racket',
      'typescript',
      'r',
      'prolog',
      'nasm',
      'swift',
      'cfml',
      'julia',
      'elixir',
      'crystal',
      'perl',
      'cobol',
      'c',
      'd',
      'factor',
      'ocaml',
      'sql',
    ],
    url: 'https://www.codewars.com/kata/5168bb5dfe9a00b126000018',
    rank: { id: -8, name: '8 kyu', color: 'white' },
    createdAt: '2013-04-13T01:56:45.991Z',
    createdBy: { username: 'jhoffner', url: 'https://www.codewars.com/users/jhoffner' },
    description:
      "Complete the solution so that it reverses the string passed into it. \n\n```\n'world'  =\u003e  'dlrow'\n'word'   =\u003e  'drow'\n```",
    totalAttempts: 391517,
    totalCompleted: 201801,
    totalStars: 1070,
    voteScore: 12542,
    tags: ['Strings', 'Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 1, suggestions: 0 },
  },
  {
    id: '554b4ac871d6813a03000035',
    name: 'Highest and Lowest',
    slug: 'highest-and-lowest',
    category: 'reference',
    publishedAt: '2015-05-07T11:50:38.518Z',
    approvedAt: '2015-05-20T03:59:32.168Z',
    languages: [
      'csharp',
      'javascript',
      'python',
      'ruby',
      'java',
      'coffeescript',
      'haskell',
      'rust',
      'typescript',
      'fsharp',
      'go',
      'kotlin',
      'php',
      'crystal',
      'cpp',
      'elixir',
      'julia',
      'r',
      'clojure',
      'c',
      'cobol',
      'scala',
      'd',
      'lua',
      'factor',
    ],
    url: 'https://www.codewars.com/kata/554b4ac871d6813a03000035',
    rank: { id: -7, name: '7 kyu', color: 'white' },
    createdAt: '2015-05-07T11:21:44.905Z',
    createdBy: { username: 'Deantwo', url: 'https://www.codewars.com/users/Deantwo' },
    approvedBy: { username: 'dnolan', url: 'https://www.codewars.com/users/dnolan' },
    description:
      'In this little assignment you are given a string of space separated numbers, and have to return the highest and lowest number.\n\n### Examples\n\n``` text\nInput: "1 2 3 4 5"   =\u003e  Output: "5 1"\nInput: "1 2 -3 4 5"  =\u003e  Output: "5 -3"\nInput: "1 9 3 4 -5"  =\u003e  Output: "9 -5"\n```\n```php\nhighAndLow("1 2 3 4 5");  // return "5 1"\nhighAndLow("1 2 -3 4 5"); // return "5 -3"\nhighAndLow("1 9 3 4 -5"); // return "9 -5"\n```\n```csharp\nKata.HighAndLow("1 2 3 4 5");  // return "5 1"\nKata.HighAndLow("1 2 -3 4 5"); // return "5 -3"\nKata.HighAndLow("1 9 3 4 -5"); // return "9 -5"\n```\n```fsharp\nhighAndLow "1 2 3 4 5"  // return "5 1"\nhighAndLow "1 2 -3 4 5" // return "5 -3"\nhighAndLow "1 9 3 4 -5" // return "9 -5"\n```\n```javascript\nhighAndLow("1 2 3 4 5");  // return "5 1"\nhighAndLow("1 2 -3 4 5"); // return "5 -3"\nhighAndLow("1 9 3 4 -5"); // return "9 -5"\n```\n```d\nhighAndLow("1 2 3 4 5");  // return "5 1"\nhighAndLow("1 2 -3 4 5"); // return "5 -3"\nhighAndLow("1 9 3 4 -5"); // return "9 -5"\n```\n```c\nhigh_and_low("1 2 3 4 5")  // return "5 1"\nhigh_and_low("1 2 -3 4 5") // return "5 -3"\nhigh_and_low("1 9 3 4 -5") // return "9 -5"\n```\n```cpp\nhighAndLow("1 2 3 4 5");  // return "5 1"\nhighAndLow("1 2 -3 4 5"); // return "5 -3"\nhighAndLow("1 9 3 4 -5"); // return "9 -5"\n```\n```typescript\nhighAndLow("1 2 3 4 5");  // return "5 1"\nhighAndLow("1 2 -3 4 5"); // return "5 -3"\nhighAndLow("1 9 3 4 -5"); // return "9 -5"\n```\n```coffeescript\nhighAndLow("1 2 3 4 5")  # return "5 1"\nhighAndLow("1 2 -3 4 5") # return "5 -3"\nhighAndLow("1 9 3 4 -5") # return "9 -5"\n```\n```python\nhigh_and_low("1 2 3 4 5")  # return "5 1"\nhigh_and_low("1 2 -3 4 5") # return "5 -3"\nhigh_and_low("1 9 3 4 -5") # return "9 -5"\n```\n```ruby\nhigh_and_low("1 2 3 4 5")  # return "5 1"\nhigh_and_low("1 2 -3 4 5") # return "5 -3"\nhigh_and_low("1 9 3 4 -5") # return "9 -5"\n```\n```crystal\nhigh_and_low("1 2 3 4 5")  # return "5 1"\nhigh_and_low("1 2 -3 4 5") # return "5 -3"\nhigh_and_low("1 9 3 4 -5") # return "9 -5"\n```\n```c\nhigh_and_low("1 2 3 4 5", result)  // result "5 1"\nhigh_and_low("1 2 -3 4 5", result) // result "5 -3"\nhigh_and_low("1 9 3 4 -5", result) // result "9 -5"\n```\n```java\nhighAndLow("1 2 3 4 5")  // return "5 1"\nhighAndLow("1 2 -3 4 5") // return "5 -3"\nhighAndLow("1 9 3 4 -5") // return "9 -5"\n```\n```haskell\nhighAndLow "1 2 3 4 5")  # return "5 1"\nhighAndLow "1 2 -3 4 5") # return "5 -3"\nhighAndLow "1 9 3 4 -5") # return "9 -5"\n```\n```go\nHighAndLow("1 2 3 4 5")  // return "5 1"\nHighAndLow("1 2 -3 4 5") // return "5 -3"\nHighAndLow("1 9 3 4 -5") // return "9 -5"\n```\n```kotlin\nhighAndLow("1 2 3 4 5")  // return "5 1"\nhighAndLow("1 2 -3 4 5") // return "5 -3"\nhighAndLow("1 9 3 4 -5") // return "9 -5"\n```\n```elixir\nKata.high_and_low("1 2 3 4 5")  # return "5 1"\nKata.high_and_low("1 2 -3 4 5") # return "5 -3"\nKata.high_and_low("1 9 3 4 -5") # return "9 -5"\n```\n```clojure\n(high-and-low "1 2 3 4 5")  ; return "5 1"\n(high-and-low "1 2 -3 4 5") ; return "5 -3"\n(high-and-low "1 9 3 4 -5") ; return "9 -5"\n```\n```julia\nhighandlow("1 2 3 4 5")  # return "5 1"\nhighandlow("1 2 -3 4 5") # return "5 -3"\nhighandlow("1 9 3 4 -5") # return "9 -5"\n```\n```rust\nhigh_and_low("1 2 3 4 5")  // return "5 1"\nhigh_and_low("1 2 -3 4 5") // return "5 -3"\nhigh_and_low("1 9 3 4 -5") // return "9 -5"\n```\n```cobol\n        HighAndLow("1 2 3 4 5")\n      * RESULT = "5 1"\n        HighAndLow("1 2 -3 4 5")\n      * RESULT = "5 -3"\n        HighAndLow("1 9 3 4 -5")\n      * RESULT = "9 -5"\n```\n```scala\nSol.high_and_low("1 2 3 4 5")  // return "5 1"\nSol.high_and_low("1 2 -3 4 5") // return "5 -3"\nSol.high_and_low("1 9 3 4 -5") // return "9 -5"\n```\n```lua\nhigh_and_low "1 2 3 4 5"   --\u003e return "5 1"\nhigh_and_low "1 2 -3 4 5"  --\u003e return "5 -3"\nhigh_and_low "1 9 3 4 -5"  --\u003e return "9 -5"\n```\n\n### Notes\n\n- All numbers are valid ```Int32```, no *need* to validate them.\n- There will always be at least one number in the input string.\n- Output string must be two numbers separated by a single space, and highest number is first.\n',
    totalAttempts: 730089,
    totalCompleted: 209478,
    totalStars: 2449,
    voteScore: 15833,
    tags: ['Fundamentals', 'Strings'],
    contributorsWanted: false,
    unresolved: { issues: 0, suggestions: 0 },
  },
  {
    id: '57eaeb9578748ff92a000009',
    name: 'Sum Mixed Array',
    slug: 'sum-mixed-array',
    category: 'reference',
    publishedAt: '2016-09-27T21:58:45.715Z',
    approvedAt: '2016-10-02T16:14:01.937Z',
    languages: [
      'javascript',
      'ruby',
      'php',
      'crystal',
      'python',
      'csharp',
      'haskell',
      'elixir',
      'java',
      'racket',
      'swift',
      'kotlin',
      'julia',
      'typescript',
      'cfml',
      'coffeescript',
      'r',
      'rust',
      'go',
    ],
    url: 'https://www.codewars.com/kata/57eaeb9578748ff92a000009',
    rank: { id: -8, name: '8 kyu', color: 'white' },
    createdAt: '2016-09-27T21:58:56.812Z',
    createdBy: { username: 'PG1', url: 'https://www.codewars.com/users/PG1' },
    approvedBy: { username: 'jhoffner', url: 'https://www.codewars.com/users/jhoffner' },
    description:
      'Given an array of integers as strings and numbers, return the sum of the array values as if all were numbers.\n\nReturn your answer as a number.',
    totalAttempts: 118272,
    totalCompleted: 53875,
    totalStars: 448,
    voteScore: 4466,
    tags: ['Fundamentals', 'Strings', 'Arrays'],
    contributorsWanted: true,
    unresolved: { issues: 1, suggestions: 1 },
  },
  {
    id: '57a2013acf1fa5bfc4000921',
    name: 'Calculate average ',
    slug: 'calculate-average',
    category: 'reference',
    publishedAt: '2016-08-03T14:35:48.901Z',
    approvedAt: '2016-10-17T16:15:50.315Z',
    languages: [
      'haskell',
      'fsharp',
      'python',
      'c',
      'csharp',
      'javascript',
      'php',
      'clojure',
      'crystal',
      'java',
      'typescript',
      'cpp',
      'nasm',
      'rust',
      'julia',
      'coffeescript',
      'r',
    ],
    url: 'https://www.codewars.com/kata/57a2013acf1fa5bfc4000921',
    rank: { id: -8, name: '8 kyu', color: 'white' },
    createdAt: '2016-08-03T14:35:38.117Z',
    createdBy: { username: 'wichu', url: 'https://www.codewars.com/users/wichu' },
    approvedBy: { username: 'suic', url: 'https://www.codewars.com/users/suic' },
    description:
      'Write a function which calculates the average of the numbers in a given list.\n\n**Note:** Empty arrays should return 0.',
    totalAttempts: 235911,
    totalCompleted: 79336,
    totalStars: 401,
    voteScore: 5875,
    tags: ['Fundamentals', 'Arrays'],
    contributorsWanted: true,
    unresolved: { issues: 6, suggestions: 1 },
  },
  {
    id: '55a70521798b14d4750000a4',
    name: 'Returning Strings',
    slug: 'returning-strings',
    category: 'reference',
    publishedAt: '2015-07-16T01:30:45.770Z',
    approvedAt: '2017-12-21T15:07:57.617Z',
    languages: [
      'python',
      'ruby',
      'cpp',
      'crystal',
      'javascript',
      'nasm',
      'php',
      'haskell',
      'scala',
      'csharp',
      'typescript',
      'lua',
      'kotlin',
      'rust',
      'sql',
      'shell',
      'go',
      'julia',
      'java',
      'groovy',
      'coffeescript',
      'swift',
      'clojure',
      'r',
      'elixir',
      'cobol',
      'ocaml',
    ],
    url: 'https://www.codewars.com/kata/55a70521798b14d4750000a4',
    rank: { id: -8, name: '8 kyu', color: 'white' },
    createdAt: '2015-07-16T01:13:05.763Z',
    createdBy: { username: 'Aweson1', url: 'https://www.codewars.com/users/Aweson1' },
    approvedBy: {
      username: 'GiacomoSorbi',
      url: 'https://www.codewars.com/users/GiacomoSorbi',
    },
    description:
      '~~~if:sql\nWrite a select statement that takes `name` from `person` table and return `"Hello, \u003cname\u003e how are you doing today?"` results in a column named `greeting`\n~~~\n~~~if-not:sql\nMake a function that will return a greeting statement that uses an input; your program should return, `"Hello, \u003cname\u003e how are you doing today?"`.\n~~~\n\n*[Make sure you type the exact thing I wrote or the program may not execute properly]*\n\n',
    totalAttempts: 209451,
    totalCompleted: 119328,
    totalStars: 384,
    voteScore: 6811,
    tags: ['Strings', 'Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 0, suggestions: 0 },
  },
  {
    id: '53ee5429ba190077850011d4',
    name: "You Can't Code Under Pressure #1",
    slug: 'you-cant-code-under-pressure-number-1',
    category: 'reference',
    publishedAt: '2014-08-15T18:40:46.276Z',
    approvedAt: '2014-08-25T03:53:31.381Z',
    languages: [
      'javascript',
      'python',
      'coffeescript',
      'ruby',
      'haskell',
      'clojure',
      'java',
      'elixir',
      'csharp',
      'nasm',
      'c',
      'cpp',
      'php',
      'prolog',
      'bf',
      'rust',
      'r',
      'cobol',
      'commonlisp',
      'erlang',
      'factor',
      'forth',
      'fortran',
      'shell',
      'crystal',
      'kotlin',
      'go',
      'julia',
      'typescript',
      'ocaml',
      'lua',
      'scala',
    ],
    url: 'https://www.codewars.com/kata/53ee5429ba190077850011d4',
    rank: { id: -8, name: '8 kyu', color: 'white' },
    createdAt: '2014-08-15T18:40:41.583Z',
    createdBy: { username: 'Kerrick', url: 'https://www.codewars.com/users/Kerrick' },
    approvedBy: { username: 'jhoffner', url: 'https://www.codewars.com/users/jhoffner' },
    description: 'Code as fast as you can! You need to double the integer and return it.',
    totalAttempts: 176613,
    totalCompleted: 109889,
    totalStars: 261,
    voteScore: 4604,
    tags: ['Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 2, suggestions: 1 },
  },
  {
    id: '515e271a311df0350d00000f',
    name: 'Square(n) Sum',
    slug: 'square-n-sum',
    category: 'reference',
    publishedAt: '2013-04-05T04:52:30.105Z',
    approvedAt: null,
    languages: [
      'javascript',
      'coffeescript',
      'ruby',
      'haskell',
      'python',
      'dart',
      'rust',
      'cpp',
      'crystal',
      'csharp',
      'nasm',
      'c',
      'php',
      'java',
      'scala',
      'julia',
      'racket',
      'elixir',
      'typescript',
      'go',
      'prolog',
      'r',
      'cfml',
      'clojure',
      'swift',
      'cobol',
      'fsharp',
      'd',
    ],
    url: 'https://www.codewars.com/kata/515e271a311df0350d00000f',
    rank: { id: -8, name: '8 kyu', color: 'white' },
    createdAt: '2013-04-05T01:21:30.396Z',
    createdBy: { username: 'jhoffner', url: 'https://www.codewars.com/users/jhoffner' },
    description:
      "Complete the square sum function so that it squares each number passed into it and then sums the results together.\n\nFor example, for `[1, 2, 2]` it should return `9` because `1^2 + 2^2 + 2^2 = 9`.\n\n```if:racket\nIn Racket, use a list instead of an array, so '(1 2 2) should return 9.\n```\n",
    totalAttempts: 369790,
    totalCompleted: 156393,
    totalStars: 1007,
    voteScore: 10679,
    tags: ['Arrays', 'Lists', 'Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 1, suggestions: 2 },
  },
  {
    id: '546e2562b03326a88e000020',
    name: 'Square Every Digit',
    slug: 'square-every-digit',
    category: 'reference',
    publishedAt: '2014-11-20T17:31:14.986Z',
    approvedAt: '2014-11-30T01:42:19.965Z',
    languages: [
      'python',
      'java',
      'javascript',
      'ruby',
      'haskell',
      'csharp',
      'crystal',
      'typescript',
      'elm',
      'julia',
      'prolog',
      'swift',
      'elixir',
      'c',
      'nasm',
      'cobol',
      'cpp',
      'r',
      'coffeescript',
      'php',
      'fsharp',
      'd',
      'rust',
      'scala',
    ],
    url: 'https://www.codewars.com/kata/546e2562b03326a88e000020',
    rank: { id: -7, name: '7 kyu', color: 'white' },
    createdAt: '2014-11-20T17:31:24.505Z',
    createdBy: {
      username: 'MysteriousMagenta',
      url: 'https://www.codewars.com/users/MysteriousMagenta',
    },
    approvedBy: { username: 'jhoffner', url: 'https://www.codewars.com/users/jhoffner' },
    description:
      'Welcome. In this kata, you are asked to square every digit of a number and concatenate them.\n\nFor example, if we run 9119 through the function, 811181 will come out, because 9\u003csup\u003e2\u003c/sup\u003e is 81 and 1\u003csup\u003e2\u003c/sup\u003e is 1.\n\n**Note:** The function accepts an integer and returns an integer\n',
    totalAttempts: 646618,
    totalCompleted: 216068,
    totalStars: 1980,
    voteScore: 17404,
    tags: ['Mathematics', 'Fundamentals'],
    contributorsWanted: true,
    unresolved: { issues: 3, suggestions: 2 },
  },
  {
    id: '525f50e3b73515a6db000b83',
    name: 'Create Phone Number',
    slug: 'create-phone-number',
    category: 'algorithms',
    publishedAt: '2013-10-17T02:52:21.801Z',
    approvedAt: null,
    languages: [
      'javascript',
      'coffeescript',
      'ruby',
      'java',
      'dart',
      'haskell',
      'csharp',
      'python',
      'scala',
      'groovy',
      'crystal',
      'powershell',
      'go',
      'c',
      'nasm',
      'rust',
      'php',
      'clojure',
      'cpp',
      'julia',
      'cfml',
      'factor',
      'fsharp',
      'cobol',
      'lua',
    ],
    url: 'https://www.codewars.com/kata/525f50e3b73515a6db000b83',
    rank: { id: -6, name: '6 kyu', color: 'yellow' },
    createdAt: '2013-10-17T02:52:19.283Z',
    createdBy: { username: 'xDranik', url: 'https://www.codewars.com/users/xDranik' },
    description:
      'Write a function that accepts an array of 10 integers (between 0 and 9), that returns a string of those numbers in the form of a phone number.\n\n### Example\n\n```javascript\ncreatePhoneNumber([1, 2, 3, 4, 5, 6, 7, 8, 9, 0]) // =\u003e returns "(123) 456-7890"\n```\n```cpp\ncreatePhoneNumber(int[10]{1, 2, 3, 4, 5, 6, 7, 8, 9, 0}) // =\u003e returns "(123) 456-7890"\n```\n```crystal\ncreate_phone_number([1, 2, 3, 4, 5, 6, 7, 8, 9, 0]) # =\u003e returns "(123) 456-7890"\n```\n```ruby\ncreatePhoneNumber([1, 2, 3, 4, 5, 6, 7, 8, 9, 0]) # =\u003e returns "(123) 456-7890"\n```\n```coffeescript\ncreatePhoneNumber([1, 2, 3, 4, 5, 6, 7, 8, 9, 0]) # =\u003e returns "(123) 456-7890"\n```\n```java\nKata.createPhoneNumber(new int[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 0}) // =\u003e returns "(123) 456-7890"\n```\n```dart\ncreatePhoneNumber([1, 2, 3, 4, 5, 6, 7, 8, 9, 0]) // =\u003e returns "(123) 456-7890"\n```\n```haskell\ncreatePhoneNumber [1,2,3,4,5,6,7,8,9,0] -- =\u003e returns "(123) 456-7890"\n```\n```csharp\nKata.CreatePhoneNumber(new int[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 0}) // =\u003e returns "(123) 456-7890"\n```\n```fsharp\ncreatePhoneNumber [1; 2; 3; 4; 5; 6; 7; 8; 9; 0] // =\u003e returns "(123) 456-7890"\n```\n```python\ncreate_phone_number([1, 2, 3, 4, 5, 6, 7, 8, 9, 0]) # =\u003e returns "(123) 456-7890"\n```\n```scala\nKata.createPhoneNumber(Seq(1, 2, 3, 4, 5, 6, 7, 8, 9, 0)) # =\u003e returns "(123) 456-7890"\n```\n```php\ncreatePhoneNumber([1,2,3,4,5,6,7,8,9,0]); // =\u003e returns "(123) 456-7890"\n```\n```f#\ncreatePhoneNumber [1; 2; 3; 4; 5; 6; 7; 8; 9; 0] // =\u003e returns "(123) 456-7890"\n```\n```clojure\n(create-phone-number [1 2 3 4 5 6 7 8 9 0]) ;; =\u003e returns "(123) 456-7890"\n```\n```rust\ncreate_phone_number(\u0026[1,2,3,4,5,6,7,8,9,0]); // returns "(123) 456-7890"\n```\n```go\nCreatePhoneNumber([10]uint{1,2,3,4,5,6,7,8,9,0})  // returns "(123) 456-7890"\n```\n```c\ncreate_phone_number(phnum, (const unsigned char[]){1,2,3,4,5,6,7,8,9,0});\n    /* phnum \u003c- "(123) 456-7890" */\n```\n```nasm\nphnum:  resb 15\nnums:   db  1,2,3,4,5,6,7,8,9,0\n\nmov rdi, phnum\nmov rsi, nums\ncall create_phone_number  ; RAX \u003c- phnum \u003c- "(123) 456-7890" \n```\n```typescript\ncreatePhoneNumber([1, 2, 3, 4, 5, 6, 7, 8, 9, 0]) // =\u003e returns "(123) 456-7890"\n```\n```julia\ncreatephonenumber([1, 2, 3, 4, 5, 6, 7, 8, 9, 0]) # -\u003e returns "(123) 456-7890"\n```\n```cfml\ncreatePhoneNumber( [1, 2, 3, 4, 5, 6, 7, 8, 9, 0] ) // =\u003e returns "(123) 456-7890"\n```\n```factor\n{ 1 2 3 4 5 6 7 8 9 0 } create-phone-number ! returns "(123) 456-7890"\n```\n```lua\ncreate_phone_number({ 1,2,3,4,5,6,7,8,9,0 }) -- =\u003e returns "(123) 456-7890"\n```\n\nThe returned format must be correct in order to complete this challenge.\n\nDon\'t forget the space after the closing parentheses!\n',
    totalAttempts: 560695,
    totalCompleted: 231966,
    totalStars: 2607,
    voteScore: 15588,
    tags: ['Arrays', 'Strings', 'Regular Expressions', 'Algorithms'],
    contributorsWanted: true,
    unresolved: { issues: 0, suggestions: 3 },
  },
];
